
disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - unused_optional_binding
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # find all the available rules by running: `swiftlint rules`
  

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - Pods
  - RickAndMorty/Sources/Generated/R.generated.swift
  - RickAndMorty/Pods
  - R.generated.swift
  
allow_zero_lintable_files: false

strict: false

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

line_length:
    warning: 120
    error: 600
    ignores_urls: true
    ignores_comments: true
    ignores_interpolated_strings: true

type_body_length:
  - 600 # warning
  - 1200 # error

file_length:
  warning: 1000
  error: 2000

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - key
    - db
    - id
    - URL
    - url
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
